# Generated by Django 5.2.10 on 2026-01-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_no', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['customer_name'],
            },
        ),
    ]
