# Generated by Django 5.2.10 on 2026-01-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_no', models.CharField(max_length=20)),
                ('item_name', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'item',
                'ordering': ['item_name'],
            },
        ),
    ]
