# Generated by Django 5.2.10 on 2026-01-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='harga',
            field=models.IntegerField(default=0),
        ),
    ]
