# Generated by Django 5.2.10 on 2026-01-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wily_add_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_no', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='app.item')),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['sales_no'],
            },
        ),
    ]
